algorithm_report.pdf:algorithm_report.tex biblio.bib
	pdflatex algorithm_report.tex
	bibtex algorithm_report.aux
	pdflatex algorithm_report.tex
	pdflatex algorithm_report.tex

view:
	zathura algorithm_report.pdf &
